export const CSideHeader = {
  // color: "#fff",
  height: 50,
  width: 300,
  position: "fixed",
  // padding: 100,
  paddingInline: 20,
  // paddingBottom:10,
  lineHeight: "auto",
  backgroundColor: "#fff",
  borderRight: "1px solid #ccc",
  boxShadow: "0 2px 8px rgba(0, 0, 0, 0.15)",
  zIndex: 8,
};
export const CHeader = {
  // textAlign: "ce",
  // color: "#fff",
  height: 50,
  width: "auto",
  backgroundColor: "#fff",
  paddingInline: 50,
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  lineHeight: "auto",
  borderBottom: "1px solid #ccc",
  // boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
  zIndex: 6,
};
export const CContent = {
  position: "",
  paddingTop: "5vh",
  // bottom:100,
  // textAlign: "center",
  // height: "100vh",
  overflow: "initial",
  // marginLeft: "auto",
  lineHeight: "auto",

  // color: "#fff",
  backgroundColor: "#fff",
};

export const CSider = {
  overflow: "auto",
  height: "auto",
  position: "fixed",
  left: 0,
  top: 50,
  bottom: 0,
  textAlign: "left",
  zIndex: 7,
  margin:"0 0 0 0",
  // paddingTop: 50,
  lineHeight: "auto",
  color: "#fff",
  backgroundColor: "#fff",
  borderRight: "1px solid #ccc",
  boxShadow: "0 2px 8px rgba(0, 0, 0, 0.15)",
};

export const CFooter = {
  textAlign: "center",
  height: "auto",
  // width: "auto",
  // paddingInline: 100,
  position: "",
  // color: "#fff",
  // backgroundColor: "",
  borderTop: "1px solid #ccc",
  boxShadow: "0 -2px 8px rgba(0, 0, 0, 0.15)",
  // // marginLeft: "auto",
  // left: 0,
  // top: 0,
  // bottom: 0,
};
